FROM node:20-alpine as builder

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install -g @angular/cli@18
RUN npm install

COPY ./client .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist/client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]
