services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.back
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
    # volumes:
    #     - ./frontend/client:/app
    ports:
      - "80:80"
